#!/bin/bash

mkdir -p build
cd build

cmake .. -G "Ninja"

START_TIME=$(date +%s)

ninja -j$(nproc)

cd ..

END_TIME=$(date +%s)
DIFF=$((END_TIME - START_TIME))
echo "Compilation Time: $DIFF seconds"
